apiVersion: v1
kind: Secret
metadata:
  name: rtct-secrets
  namespace: rtct
type: Opaque
stringData:
  POSTGRES_PASSWORD: "postgres"
  PGPASSWORD: "postgres"
  JWT_SECRET: "dev-jwt-secret-12345"
  dev-jwt-secret: "dev-jwt-secret-12345"
  INTERNAL_ALERT_TOKEN: "super-secret-string"
  INTERNAL_API_KEY: "super-secret-string"
