apiVersion: v1
kind: Secret
metadata:
  name: rtct-secrets
  namespace: rtct
type: Opaque
stringData:
  POSTGRES_PASSWORD: "postgres"
  JWT_SECRET: "dev-jwt-secret-12345"
  dev-jwt-secret: "dev-jwt-secret-12345"
  INTERNAL_ALERT_TOKEN: "b862d2b4f286bfe0ace308a577b402fce3fca9a94980509cdd5a7d7995089568"
  INTERNAL_API_KEY: "super-secret-string"
  PGPASSWORD: "postgres"
