apiVersion: v1
kind: ConfigMap
metadata:
  name: rtct-config
  namespace: rtct
data:
  JWT_EXPIRES_IN: 1d

  POSTGRES_DB: rtct
  POSTGRES_HOST: db
  POSTGRES_PORT: "5432"
  POSTGRES_USER: postgres

  PGHOST: db
  PGPORT: "5432"
  PGUSER: postgres
  PGDATABASE: rtct
