apiVersion: v1
kind: ConfigMap
metadata:
  name: rtct-config
  namespace: rtct
data:
  POSTGRES_DB: rtct
  POSTGRES_USER: postgres
  POSTGRES_HOST: postgres
  POSTGRES_PORT: "5432"
  JWT_EXPIRES_IN: "1d"
