apiVersion: apps/v1
kind: Deployment
metadata:
  name: rtct-web
  namespace: rtct
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rtct-web
  template:
    metadata:
      labels:
        app: rtct-web
    spec:
      nodeSelector:
        kubernetes.io/hostname: attack-pi
      containers:
        - name: rtct-web
          image: jaxmerc536/rtct-dashboard:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: rtct
spec:
  selector:
    app: rtct-web
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP
