version: "3.9"

services:
  db:
    image: postgres:18
    container_name: pg
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rtct
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    container_name: rtct-api
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "4000:4000"
    restart: always

volumes:
  pgdata:
